### ISSUE TITLE
A pre-fork

### ISSUE THREAD

**Issue by mtancoigne** [inkline/vue-cli-plugin-inkline#1]
We can't fork empty repos, so I created one so you can track and comment on it until you're happy with it:

https://github.com/el-cms/wip-vue-cli-plugin-inkline/pull/1

**Comment by alexgrozav** [comment]
Looking great so far. I've created an empty readme come so you can create a PR to this repository.

**Comment by mtancoigne** [comment]
Everything is now merged in master :) Long life to this plugin :tada:
