### ISSUE TITLE
Updates for Inkline

### ISSUE THREAD

**Issue by mtancoigne** [inkline/vue-cli-plugin-inkline#4]
Hi!

I see that Inkline had a recent version bump; do we need to update the plugin too ? 

I never maintained plugins to install something, so I don't know if it's relevant to update the version noted `'@inkline/inkline': '^1.14'` when it updates to `1.15`

**Comment by alexgrozav** [comment]
Hey! To be honest, I don't know. When using the up arrow `^`, the minor version will always be kept up to date when running `npm update` and `npm install`, meaning that it should be installing 1.15, but I guess we'll have to check this behaviour to be sure.

**Comment by mtancoigne** [comment]
Modifications to the lockfile after `vue add inkline` on a fresh project
```diff
+"@inkline/inkline@^1.14":
+  version "1.15.1"
+  resolved "https://registry.yarnpkg.com/@inkline/inkline/-/inkline-1.15.1.tgz#b4e11ca6177ae863ce55aebbaa09669830143ddf"
+  integrity sha512-0XZmxyJ47HNSwcQJP6+ei375b2uwmh0jo94cgxPSIa+iBtlEV4zr9rcJ0Sy+DB96p7VliQl3ov/goA3xo8UJqw==
```

That answers the question.
